### ISSUE TITLE
Outline pattern question

### ISSUE THREAD

**Issue by pocketcap** [lillallol/outline-pdf-cjs#1]
First thanks for creating this module that makes adding Bookmark/Outline easier in PDF.

For the outline pattern you give in https://github.com/lillallol/outline-pdf-cjs#example, seems like you have to put titles for all the pages, right? As I got errors if I didn't specify title for all the pages. For example, my PDF has 5 pages, but I only have 4 page titles like:
         1||Title 1
         2|-|Title 2
        -3|--|Title 3
         4|---|Title 4
Doing this would give me the error "TypeError: Cannot destructure property `Title` of 'undefined' or 'null'." 

Any help would be appreciated :)

**Comment by lillallol** [comment]
@pocketcap 

I pushed an update to fix the bug in one of the dependencies of the package. Uninstall and then re install `outline-pdf-cjs`. Check if it solves your issue and let me know.

**Comment by pocketcap** [comment]
@lillallol I tried, but still same.

Btw, that's how I have code as:
```
const { outlinePdfCjs } = require("@lillallol/outline-pdf-cjs");

async function creatOutlines() {
  await outlinePdfCjs({
      loadPath: "in.pdf",
      savePath: "outout.pdf",
      // first column  : page number
      //                 negative for collapsing outline
      // second column : outline depth
      // third column  : outline title
      outline: `
          1||Title 1
          2|-|Title 2
          -3|--|Title 3
          4|---|Title 4
          5|---|Title 5
          6|-|Title 6
          7||Title 7
      `,
  });
}

creatOutlines();
```

**Comment by lillallol** [comment]
@pocketcap 

I updated the package dependencies so it should work now. So uninstall the package and install it again. If the problem persists let me know.

**Comment by pocketcap** [comment]
@lillallol Thanks for fixing it. Yeah, I tried the new package, and it does solve the issue.
But I got new error if title number is larger than page number. Say I have 5 pages in PDF, but I have 7 titles specified. It give me error:
```
(node:21344) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'objectNumber' of undefined
    at PDFContext.assign (C:\git\formio-sql-service\node_modules\pdf-lib\cjs\core\PDFContext.js:34:17)
    at Object.applyOutlineToPdf (C:\git\formio-sql-service\node_modules\@lillallol\outline-pdf-cjs\node_modules\@lillallol\outline-pdf\dist\outlinePdf\outlinePdfFactory.js:84:29)
    at outlinePdfCjs (C:\git\formio-sql-service\node_modules\@lillallol\outline-pdf-cjs\dist\index.js:21:16)
    at async creatOutlines (C:\git\formio-sql-service\src\test\outline.js:4:3)
```

**Comment by lillallol** [comment]
@pocketcap 

I made some changes. Now it should work. Uninstal and reinstall and then let me know if it fixes your issue.

**Comment by pocketcap** [comment]
@lillallol It's working great now~ Thanks!
